apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: your-docker-repo/server:latest
        env:
        - name: CarApiConnection
          value: "Server=host.docker.internal;Initial Catalog=CarDb;Integrated Security=True;Max Pool Size=100;Encrypt=false"
        - name: QueueDbConnection
          value: "Server=host.docker.internal;Initial Catalog=QueueDb;Integrated Security=True;Max Pool Size=100;Encrypt=false"
